[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"

[build]
    # Directory (relative to root of your repo) that contains the deploy-ready HTML files
    publish = "_site"
    
    # Build command
    command = "npm run build"
